spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    name: jpa

  banner:
    location: banner.txt  #指定banner的文件位置

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true #解决懒加载时，缺少session的问题
        format_sql: true
        ddl_auto: true

  redis:
    host: 127.0.0.1
    database: 0
    ssl: false
    port: 7000
    cluster:
      # redis集群的ip和端口
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      max-redirects: 1 #集群最大跳转次数
    jedis:
      pool:
        max-active: 8 #线程池中最大线程数
        min-idle: 2 #最大空闲线程数
    timeout: 5000ms

server:
  port: 8081  #服务的端口

logging:
  level:
    root: info  #日志的打印级别

management:
  endpoint:
    shutdown:
      enabled: true #开启actuator的shutdown端点