spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    name: jpa
  banner:
    location: banner.txt
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true #解决缺少session的问题
        format_sql: true
        ddl_auto: true

  redis:
    host: 127.0.0.1
    database: 0
    ssl: false
    port: 6379

server:
  port: 8081

logging:
  level:
    rog.springframeword: debug
    root: debug